### ISSUE TITLE
Problems on downloading data

### ISSUE THREAD

**Issue by mpiffari** [aruns2120/Semantic-Segmentation-Severstal#2]
Hi @aruns2120 ,
I'm here to ask your help on running U seg notebook: in fact, in the very first cells, I get an error during the download of the dataset.
The error is:
`--2020-12-02 16:02:26--  https://storage.googleapis.com/kaggle-competitions-data/kaggle-v2/14241/862020/bundle/archive.zip?GoogleAccessId=web-data@kaggle-161607.iam.gserviceaccount.com&Expires=1585378453&Signature=h2F1NAm4R%2BE47ciKVCqoApTJuHaq0irbA7Yk1XiDNPhA3Ap6%2Fam2%2BK%2BBB5BNRCsz7oRumb16ZVH%2BHGu3TYeXLhHbvrsD%2BdbpV85mf4YzaEnqmhD3Bk3RGj3%2BHC%2B9%2BjVExFA1h60vxEiBCWs0YriI5UwblPZ0GFVAxdd3L2yNJGR5Jl36%2FVP7MkdSeXOdP4SjFysy1kldd4OujZbiCu%2FspOxCZo3UCRS21LhQVVJaG7PPNXABkp%2FzIzzE7yEI9SqnByvPQO3Kzt965r3e38Qo9XcXHya32v4KGKKN3fN3KiQis%2B4qJf55azjryGTYo8MOcEwhVmIw0wZbCXvRxntmEw%3D%3D&response-content-disposition=attachment%3B+filename%3Dseverstal-steel-defect-detection.zip
Resolving storage.googleapis.com (storage.googleapis.com)... 172.217.7.176, 172.217.12.240, 172.217.15.112, ...
Connecting to storage.googleapis.com (storage.googleapis.com)|172.217.7.176|:443... connected.
HTTP request sent, awaiting response... 400 Bad Request
2020-12-02 16:02:27 ERROR 400: Bad Request.`

Can you help me?

**Comment by aruns2120** [comment]
Hi @Piffo
This error came because the API extension (CurlWget) that I had used for downloading seems to be no longer available.
I have now changed the script slightly (used plain wget), and it works fine now.
Can you please try running again?
Cheers 😊

**Comment by mpiffari** [comment]
Hi @aruns2120 ,
yes, the download phase seems to be ok now.

I've found another problem with tqdm_notebook in section 3.2.2, look here:
`
<ipython-input-12-72831d873179> in <module>()
      1 image_size = [] #list of tuples containing shape(height, width, channel) of images
----> 2 for image_id in tqdm_notebook(listdir('train_images')):
      3     img = cv2.imread("train_images/"+image_id)
      4     h, w, c = img.shape
      5 

NameError: name 'tqdm_notebook' is not defined`
Probably the problem is that we need to use tdqm witouth "_notebook"?

EDIT: I confirm that is a typo error, but I'm facing some problem on "fit_generator" command.

**Comment by aruns2120** [comment]
Hi @Piffo 

Yes, that was a typo. Thanks for pointing out, I have changed it now.
I tried running the notebook at my end and everything seems to be working perfectly fine including 'fit_generator'.

Please note that this notebook has been authored in **Tensorflow version 1.x**. Therefore, I would suggest you to make sure you are using Tensorflow 1.x in order to avoid errors.
If you are using Google Colaboratory, you just need to include the below line before importing Tensorflow to use Tensorflow 1.x.

`%tensorflow_version 1.x`

I have included this in the latest commit of the notebook.

**Comment by mpiffari** [comment]
Hi @aruns2120 ,
thanks for your attention and feedback.

Yeah, the next question would be "which version of tensor flow are you using?": I'll try to use 1.x version and after, if all goes well, I'll close the issue.

Thank you @aruns2120!

**Comment by aruns2120** [comment]
Hi @Piffo, 
I am using **Tensorflow version 1.15.2**

Thanks 😊

**Comment by mpiffari** [comment]
Hi @aruns2120,
Starting from today, running the Colab, I face the problem on API.
Could you check it?

Cheers, Michele

**Comment by aruns2120** [comment]
Hi @Piffo ,
Replacing the download URL with a fresh URL should solve the issue. The way I do it is click on Download on Kaggle Dataset page, then cancel the download and copy the download URL and paste it in --referer = '     '
If this sounds confusing, refer to below steps:

**Step 1: Click on Download button/link on Kaggle Dataset page.**

![image](https://user-images.githubusercontent.com/62033327/102706775-cd42f600-42ba-11eb-8e22-7138f8bd25dd.png)


**Step 2: Cancel the Download**

![image](https://user-images.githubusercontent.com/62033327/102706838-6114c200-42bb-11eb-9fe4-bcb731e9599e.png)


**Step 3: Go to Downloads in your browser, right click and copy the URL of the download you just cancelled.**

![image](https://user-images.githubusercontent.com/62033327/102706954-7c340180-42bc-11eb-80ed-4d61541a01a6.png)


**Step 4: Paste it in your code against --referer== '  ' . Make sure you put the URL within quotes.**

![image](https://user-images.githubusercontent.com/62033327/102707000-0a0fec80-42bd-11eb-83b4-3e1609a3ee65.png)

**Comment by aruns2120** [comment]
Alternatively, you can try the method mentioned in this article.
[https://medium.com/analytics-vidhya/how-to-directly-download-kaggle-dataset-to-google-drive-aa06175712e2](url)
